### PR TITLE
TextOnly Filter

### PR DESCRIPTION
**Pull request by copoer**
For those who do not want any text formatting except new lines

### CODE REVIEW

**Comment by TheQuinbox** [comment]
@jaytaylor, it looks like this would close #52. Is there a reason it hasn't been merged yet?

**Comment by iredmail** [comment]
I need this feature too, hopefully this could be merged. :)

btw, is it better to rename `JustText` to `TextOnly`?

**Comment by Kleissner** [comment]
`TextOnly` definitely makes more sense.

**Comment by jaytaylor** [comment]
@copoer Happy to work together to get this merged!  Are you able to (pretty please) squash it into a single commit?

**Comment by iredmail** [comment]
> Are you able to (pretty please) squash it into a single commit?

GitHub offers a button to squash the commands and merge, that means you can do it directly by one click. :)

**Comment by jaytaylor** [comment]
This is true, but would this lead to a commit history polluted with WIP?  OP - please clean up and squash the commits so we can merge this baby

**Comment by iredmail** [comment]
> This is true, but would this lead to a commit history polluted with WIP?

No. Only one commit after merged. :)

**Comment by iredmail** [comment]
By the way, could you tag a new version after merged this PR?
It would be great to use Go module too, see #42

**Comment by jaytaylor** [comment]
Beautiful!  Thank you @copoer !!!!!

**Comment by jaytaylor** [comment]
> By the way, could you tag a new version after merged this PR? It would be great to use Go module too, see #42

@iredmail I'm on it, haven't created tags for my go libraries before but let's give it a shot.  I will follow up in #42.

**Pull request merged**
