### PR TITLE
Fix #14

### LINKED ISSUE #14: Use of https://github.com/olekukonko/tablewriter to write beautiful table
Hello,

I'm maintainer of [Hermes](https://github.com/matcornic/hermes), a Golang package that generates clean, responsive HTML e-mails for sending transactional mail.

I'm thinking about using your really nice package to help generate plain text email as fallbacks of HTML ones. Everything is working great, but generated tables are not as clean as I would want.

Would you replace its implementation with https://github.com/olekukonko/tablewriter ?

For example, 

1. Given: a [table like this](https://github.com/matcornic/hermes/blob/master/screens/default/receipt.png)

2. Actual result, using current version of html2text :

```
Item Description Price
Golang Open source programming language that makes it easy to build simple, reliable, and efficient software $10.99
Hermes Programmatically create beautiful e-mails using Golang. $1.99
```

3. Expected result, using https://github.com/olekukonko/tablewriter

```
+--------+--------------------------------+--------+
|  ITEM  |          DESCRIPTION           | PRICE  |
+--------+--------------------------------+--------+
| Golang | Open source programming        | $10.99 |
|        | language that makes it easy    |        |
|        | to build simple, reliable, and |        |
|        | efficient software             |        |
| Hermes | Programmatically create        | $1.99  |
|        | beautiful e-mails using Golang |        |
+--------+--------------------------------+--------+
```

Btw, thank you for the great work :)

### PR DESCRIPTION
**Pull request by matcornic**

### CODE REVIEW

**Comment by matcornic** [comment]
Suggest you to squash the commits, I added/fixed comments in 2 more commits ^^

**Comment by matcornic** [comment]
It's actually a WIP, as I'm waiting for your feedback. If everything is OK for you, I'll add examples in the README.

**Comment by jaytaylor** [comment]
@matcornic It looks like you're close.  Would you mind squashing them on your end once this is ready?

screen shot 2017-05-22 at 1 55 08 pm

**Comment by jaytaylor** [comment]
@matcornic It looks like you're close.  Would you mind squashing them on your end once it's ready?

screen shot 2017-05-22 at 1 55 08 pm

**Comment by jaytaylor** [comment]
@matcornic So far it's looking pretty good to me!

**Comment by matcornic** [comment]
@jaytaylor squashed and ready !

**Comment by jaytaylor** [comment]
@matcornic Way to go, this is excellent work!

Thank you, it's been a pleasure.

Fixes #14.

**Pull request merged**
